---
# CML-related variables
cml_host: "cml-hostname-here"
cml_username: "cml-username-here"
cml_password: "cml-password-here"
cml_lab_filename: "Pluralsight ITSM Course.yaml"
cml_lab_filepath: "../files/{{ cml_lab_filename }}"

# ServiceNow-related variables
servicenow_host: "https://servicenow-instance-here.service-now.com"
servicenow_username: "servicenow-username-here"
servicenow_password: "servicenow-password-here"

# Jira-related variables
jira_uri: "https://jira-instance-here.atlassian.net"
jira_username: "jira-username-here"
jira_password: "jira-token-here"
