---
- name: Close an existing ServiceNow incident
  hosts: localhost
  tasks:
    - name: Resolve ServiceNow incident
      servicenow.itsm.incident:
        instance:
          host: "{{ servicenow_host }}"
          username: "{{ servicenow_username }}"
          password: "{{ servicenow_password }}"
        number: "INC0010004"
        state: "resolved"
        close_code: "Solved (Work Around)"
        close_notes: "Workaround identified, resolving incident via automation."

    - name: Close ServiceNow incident
      servicenow.itsm.incident:
        instance:
          host: "{{ servicenow_host }}"
          username: "{{ servicenow_username }}"
          password: "{{ servicenow_password }}"
        number: "INC0010004"
        state: "closed"
        close_code: "Solved (Permanently)"
        close_notes: "Issue solved, closing incident via automation."
