---
- name: Create a new ServiceNow incident
  hosts: localhost
  tasks:
    - name: Create ServiceNow incident
      servicenow.itsm.incident:
        instance:
          host: "{{ servicenow_host }}"
          username: "{{ servicenow_username }}"
          password: "{{ servicenow_password }}"
        state: "new"
        short_description: "Incident automatically opened by Ansible."
        impact: "low"
        urgency: "low"
