---
- name: >-
    Troubleshoot connectivity between a source IP address and a destination IP
    address
  hosts: routers
  tasks:
    - name: "Identify router where source IP is attached"
      cisco.ios.ios_command:
        commands: "show ip cef {{ source_ip }} | include attached"
      register: ingress_cef_output
    - name: "Identify ingress router based on CEF output"
      ansible.builtin.set_fact:
        ingress_router: "{{ inventory_hostname }}"
      when: ingress_cef_output.stdout[0]
    - name: "Identify router where destination IP is attached"
      cisco.ios.ios_command:
        commands: "show ip cef {{ destination_ip }} | include attached"
      register: egress_cef_output
    - name: "Identify egress router based on CEF output"
      ansible.builtin.set_fact:
        egress_router: "{{ inventory_hostname }}"
      when: egress_cef_output.stdout[0]
    - name: >-
        Update ServiceNow incident with troubleshooting information from
        ingress router
      block:
        - name: >-
            Update ServiceNow incident with basic information
            about ingress router
          servicenow.itsm.incident:
            instance:
              host: "{{ servicenow_host }}"
              username: "{{ servicenow_username }}"
              password: "{{ servicenow_password }}"
            number: "{{ servicenow_record }}"
            other:
              work_notes: >-
                The ingress router for flows from {{ source_ip }} to
                {{ destination_ip }} has been identified as
                {{ ingress_router }} based on the router's CEF output.


                This router is a Cisco {{ ansible_net_model }} running IOS-XE
                {{ ansible_net_version }} with serial number
                {{ ansible_net_serialnum }}.
        - name: "Ping source IP from ingress router"
          cisco.ios.ios_ping:
            dest: "{{ source_ip }}"
          register: ingress_ping_source_ip
        - name: >-
            Update ServiceNow incident with information about ICMP
            ping from ingress router to source IP when reachability is working
            and reliable.
          servicenow.itsm.incident:
            instance:
              host: "{{ servicenow_host }}"
              username: "{{ servicenow_username }}"
              password: "{{ servicenow_password }}"
            number: "{{ servicenow_record }}"
            other:
              work_notes: >-
                {{ ingress_ping_source_ip.packets_tx }} ICMP Echo Request
                packets were sent from router {{ ingress_router }} to
                {{ source_ip }}, and {{ ingress_ping_source_ip.packets_rx }}
                ICMP Echo Reply packets were received in response. This
                indicates that {{ ingress_router }} has reliable connectivity
                to {{ source_ip }}
          when: >-
            ingress_ping_source_ip.packets_tx ==
            ingress_ping_source_ip.packets_rx
        - name: >-
            Update ServiceNow incident with information about ICMP
            ping from ingress router to source IP when reachability is working,
            but unreliable.
          servicenow.itsm.incident:
            instance:
              host: "{{ servicenow_host }}"
              username: "{{ servicenow_username }}"
              password: "{{ servicenow_password }}"
            number: "{{ servicenow_record }}"
            other:
              work_notes: >-
                {{ ingress_ping_source_ip.packets_tx }} ICMP Echo Request
                packets were sent from ingress router {{ ingress_router }} to
                {{ source_ip }}, but only
                {{ ingress_ping_source_ip.packets_rx }} ICMP Echo Reply packets
                were received in response. This indicates that
                {{ ingress_router }} has connectivity to {{ source_ip }}, but
                the connectivity is not reliable.
          when: >-
            ingress_ping_source_ip.packets_tx <
            ingress_ping_source_ip.packets_rx
            and not ingress_ping_source_ip.packets_rx == 0
        - name: >-
            Update ServiceNow incident with information about ICMP
            ping from ingress router to source IP when reachability is not
            working at all.
          servicenow.itsm.incident:
            instance:
              host: "{{ servicenow_host }}"
              username: "{{ servicenow_username }}"
              password: "{{ servicenow_password }}"
            number: "{{ servicenow_record }}"
            other:
              work_notes: >-
                {{ ingress_ping_source_ip.packets_tx }} ICMP Echo Request
                packets were sent from ingress router {{ ingress_router }} to
                {{ source_ip }}, but {{ ingress_ping_source_ip.packets_rx }}
                ICMP Echo Reply packets were received in response. This
                indicates that {{ ingress_router }} has no connectivity to
                {{ source_ip }}.
          when: >-
            ingress_ping_source_ip.packets_tx <
            ingress_ping_source_ip.packets_rx
            and ingress_ping_source_ip.packets_rx == 0
        - name: "Ping destination IP from ingress router"
          cisco.ios.ios_ping:
            dest: "{{ destination_ip }}"
          register: ingress_ping_destination_ip
        - name: >-
            Update ServiceNow incident with information about ICMP
            ping from ingress router to source IP when reachability is working
            and reliable.
          servicenow.itsm.incident:
            instance:
              host: "{{ servicenow_host }}"
              username: "{{ servicenow_username }}"
              password: "{{ servicenow_password }}"
            number: "{{ servicenow_record }}"
            other:
              work_notes: >-
                {{ ingress_ping_destination_ip.packets_tx }} ICMP Echo Request
                packets were sent from router {{ ingress_router }} to
                {{ destination_ip }}, and
                {{ ingress_ping_destination_ip.packets_rx }} ICMP Echo Reply
                packets were received in response. This indicates that
                {{ ingress_router }} has reliable connectivity to
                {{ destination_ip }}
          when: >-
            ingress_ping_destination_ip.packets_tx ==
            ingress_ping_destination_ip.packets_rx
        - name: >-
            Update ServiceNow incident with information about ICMP
            ping from ingress router to source IP when reachability is working,
            but unreliable.
          servicenow.itsm.incident:
            instance:
              host: "{{ servicenow_host }}"
              username: "{{ servicenow_username }}"
              password: "{{ servicenow_password }}"
            number: "{{ servicenow_record }}"
            other:
              work_notes: >-
                {{ ingress_ping_destination_ip.packets_tx }} ICMP Echo Request
                packets were sent from ingress router {{ ingress_router }} to
                {{ destination_ip }}, but only
                {{ ingress_ping_destination_ip.packets_rx }} ICMP Echo Reply
                packets were received in response. This indicates that
                {{ ingress_router }} has connectivity to {{ destination_ip }},
                but the connectivity is not reliable.
          when: >-
            ingress_ping_destination_ip.packets_tx <
            ingress_ping_destination_ip.packets_rx
            and not ingress_ping_destination_ip.packets_rx == 0
        - name: >-
            Update ServiceNow incident with information about ICMP
            ping from ingress router to source IP when reachability is not
            working at all.
          servicenow.itsm.incident:
            instance:
              host: "{{ servicenow_host }}"
              username: "{{ servicenow_username }}"
              password: "{{ servicenow_password }}"
            number: "{{ servicenow_record }}"
            other:
              work_notes: >-
                {{ ingress_ping_destination_ip.packets_tx }} ICMP Echo Request
                packets were sent from ingress router {{ ingress_router }} to
                {{ destination_ip }}, but
                {{ ingress_ping_destination_ip.packets_rx }} ICMP Echo Reply
                packets were received in response. This indicates that
                {{ ingress_router }} has no connectivity to
                {{ destination_ip }}.
          when: >-
            ingress_ping_destination_ip.packets_tx <
            ingress_ping_destination_ip.packets_rx
            and ingress_ping_destination_ip.packets_rx == 0
        - name: "Trace route to destination IP from ingress router"
          cisco.ios.ios_command:
            commands: "traceroute {{ destination_ip }}"
          register: ingress_traceroute_destination_ip
        - name: "Update ServiceNow incident"
          servicenow.itsm.incident:
            instance:
              host: "{{ servicenow_host }}"
              username: "{{ servicenow_username }}"
              password: "{{ servicenow_password }}"
            number: "{{ servicenow_record }}"
            other:
              work_notes: >-
                Traceroute output from {{ ingress_router }} towards
                {{ destination_ip }}:


                [code]<pre>
                `traceroute {{ destination_ip }}`<br />
                {{ ingress_traceroute_destination_ip.stdout_lines[0]
                | join("<br />") }}
                </pre>[/code]
      when: ingress_router is defined and ingress_router == inventory_hostname
    - name: >-
        Update ServiceNow incident with troubleshooting information from
        egress router
      block:
        - name: >-
            Update ServiceNow incident with basic information
            about egress router
          servicenow.itsm.incident:
            instance:
              host: "{{ servicenow_host }}"
              username: "{{ servicenow_username }}"
              password: "{{ servicenow_password }}"
            number: "{{ servicenow_record }}"
            other:
              work_notes: >-
                The egress router for flows from {{ source_ip }} to
                {{ destination_ip }} has been identified as {{ egress_router }}
                based on the router's CEF output.


                This router is a Cisco {{ ansible_net_model }} running IOS-XE
                {{ ansible_net_version }} with serial number
                {{ ansible_net_serialnum }}.
        - name: "Ping source IP from egress router"
          cisco.ios.ios_ping:
            dest: "{{ source_ip }}"
          register: egress_ping_source_ip
        - name: >-
            Update ServiceNow incident with information about ICMP
            ping from ingress router to source IP when reachability is working
            and reliable.
          servicenow.itsm.incident:
            instance:
              host: "{{ servicenow_host }}"
              username: "{{ servicenow_username }}"
              password: "{{ servicenow_password }}"
            number: "{{ servicenow_record }}"
            other:
              work_notes: >-
                {{ egress_ping_source_ip.packets_tx }} ICMP Echo Request
                packets were sent from router {{ egress_router }} to
                {{ source_ip }}, and {{ egress_ping_source_ip.packets_rx }}
                ICMP Echo Reply packets were received in response. This
                indicates that {{ egress_router }} has reliable connectivity
                to {{ source_ip }}
          when: >-
            egress_ping_source_ip.packets_tx ==
            egress_ping_source_ip.packets_rx
        - name: >-
            Update ServiceNow incident with information about ICMP
            ping from ingress router to source IP when reachability is working,
            but unreliable.
          servicenow.itsm.incident:
            instance:
              host: "{{ servicenow_host }}"
              username: "{{ servicenow_username }}"
              password: "{{ servicenow_password }}"
            number: "{{ servicenow_record }}"
            other:
              work_notes: >-
                {{ egress_ping_source_ip.packets_tx }} ICMP Echo Request
                packets were sent from ingress router {{ egress_router }} to
                {{ source_ip }}, but only
                {{ egress_ping_source_ip.packets_rx }} ICMP Echo Reply packets
                were received in response. This indicates that
                {{ egress_router }} has connectivity to {{ source_ip }}, but
                the connectivity is not reliable.
          when: >-
            egress_ping_source_ip.packets_tx <
            egress_ping_source_ip.packets_rx
            and not egress_ping_source_ip.packets_rx == 0
        - name: >-
            Update ServiceNow incident with information about ICMP
            ping from ingress router to source IP when reachability is not
            working at all.
          servicenow.itsm.incident:
            instance:
              host: "{{ servicenow_host }}"
              username: "{{ servicenow_username }}"
              password: "{{ servicenow_password }}"
            number: "{{ servicenow_record }}"
            other:
              work_notes: >-
                {{ egress_ping_source_ip.packets_tx }} ICMP Echo Request
                packets were sent from ingress router {{ egress_router }} to
                {{ source_ip }}, but {{ egress_ping_source_ip.packets_rx }}
                ICMP Echo Reply packets were received in response. This
                indicates that {{ egress_router }} has no connectivity to
                {{ source_ip }}.
          when: >-
            egress_ping_source_ip.packets_tx <
            egress_ping_source_ip.packets_rx
            and egress_ping_source_ip.packets_rx == 0
        - name: "Ping destination IP from egress router"
          cisco.ios.ios_ping:
            dest: "{{ destination_ip }}"
          register: egress_ping_destination_ip
        - name: >-
            Update ServiceNow incident with information about ICMP
            ping from ingress router to source IP when reachability is working
            and reliable.
          servicenow.itsm.incident:
            instance:
              host: "{{ servicenow_host }}"
              username: "{{ servicenow_username }}"
              password: "{{ servicenow_password }}"
            number: "{{ servicenow_record }}"
            other:
              work_notes: >-
                {{ egress_ping_destination_ip.packets_tx }} ICMP Echo Request
                packets were sent from router {{ egress_router }} to
                {{ destination_ip }}, and
                {{ egress_ping_destination_ip.packets_rx }} ICMP Echo Reply
                packets were received in response. This indicates that
                {{ egress_router }} has reliable connectivity to
                {{ destination_ip }}
          when: >-
            egress_ping_destination_ip.packets_tx ==
            egress_ping_destination_ip.packets_rx
        - name: >-
            Update ServiceNow incident with information about ICMP
            ping from ingress router to source IP when reachability is working,
            but unreliable.
          servicenow.itsm.incident:
            instance:
              host: "{{ servicenow_host }}"
              username: "{{ servicenow_username }}"
              password: "{{ servicenow_password }}"
            number: "{{ servicenow_record }}"
            other:
              work_notes: >-
                {{ egress_ping_destination_ip.packets_tx }} ICMP Echo Request
                packets were sent from ingress router {{ egress_router }} to
                {{ destination_ip }}, but only
                {{ egress_ping_destination_ip.packets_rx }} ICMP Echo Reply
                packets were received in response. This indicates that
                {{ egress_router }} has connectivity to {{ destination_ip }},
                but the connectivity is not reliable.
          when: >-
            egress_ping_destination_ip.packets_tx <
            egress_ping_destination_ip.packets_rx
            and not egress_ping_destination_ip.packets_rx == 0
        - name: >-
            Update ServiceNow incident with information about ICMP
            ping from ingress router to source IP when reachability is not
            working at all.
          servicenow.itsm.incident:
            instance:
              host: "{{ servicenow_host }}"
              username: "{{ servicenow_username }}"
              password: "{{ servicenow_password }}"
            number: "{{ servicenow_record }}"
            other:
              work_notes: >-
                {{ egress_ping_destination_ip.packets_tx }} ICMP Echo Request
                packets were sent from ingress router {{ egress_router }} to
                {{ destination_ip }}, but
                {{ egress_ping_destination_ip.packets_rx }} ICMP Echo Reply
                packets were received in response. This indicates that
                {{ egress_router }} has no connectivity to
                {{ destination_ip }}.
          when: >-
            egress_ping_destination_ip.packets_tx <
            egress_ping_destination_ip.packets_rx
            and egress_ping_destination_ip.packets_rx == 0
        - name: "Trace route to source IP from egress router"
          cisco.ios.ios_command:
            commands: "traceroute {{ source_ip }}"
          register: egress_traceroute_source_ip
        - name: "Update ServiceNow incident"
          servicenow.itsm.incident:
            instance:
              host: "{{ servicenow_host }}"
              username: "{{ servicenow_username }}"
              password: "{{ servicenow_password }}"
            number: "{{ servicenow_record }}"
            other:
              work_notes: >-
                Traceroute output from {{ egress_router }} towards
                {{ source_ip }}:


                [code]<pre>
                `traceroute {{ source_ip }}`<br />
                {{ egress_traceroute_source_ip.stdout_lines[0]
                | join("<br />") }}
                </pre>[/code]
      when: egress_router is defined and egress_router == inventory_hostname
