---
- name: "Create, update, and close a Jira problem"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Create Jira problem"
      community.general.jira:
        uri: "{{ jira_uri }}"
        username: "{{ jira_username }}"
        password: "{{ jira_password }}"
        project: "GLOB"
        operation: "create"
        summary: "Example Problem"
        description: >
          Problem automatically opened by Ansible demonstrating how Ansible
          can open a new problem.
        issuetype: "[System] Problem"
        fields:
          labels:
            - ansible
      register: results
    - ansible.builtin.pause:
        prompt: "Press 'Enter' to continue with playbook"
    - name: "Display results of Jira creation"
      ansible.builtin.debug:
        var: results
    - ansible.builtin.pause:
        prompt: "Press 'Enter' to continue with playbook"
    - name: "Display Jira issue key"
      ansible.builtin.debug:
        var: results.meta.key
    - ansible.builtin.pause:
        prompt: "Press 'Enter' to continue with playbook"
    - name: "Assign Jira problem to user account"
      community.general.jira:
        uri: "{{ jira_uri }}"
        username: "{{ jira_username }}"
        password: "{{ jira_password }}"
        issue: "{{ results.meta.key }}"
        operation: "transition"
        status: "Review"
        account_id: "70121:2dbae1f5-6dca-4b0f-bc3d-353c20e542d2"
    - ansible.builtin.pause:
        prompt: "Press 'Enter' to continue with playbook"
    - name: "Move Jira problem to Under Investigation status and add notes"
      community.general.jira:
        uri: "{{ jira_uri }}"
        username: "{{ jira_username }}"
        password: "{{ jira_password }}"
        issue: "{{ results.meta.key }}"
        operation: "transition"
        status: "Investigate"
        comment: "Attempting to automatically identify root cause of issue."
    - ansible.builtin.pause:
        prompt: "Press 'Enter' to continue with playbook"
    - name: "Complete/Resolve Jira problem"
      community.general.jira:
        uri: "{{ jira_uri }}"
        username: "{{ jira_username }}"
        password: "{{ jira_password }}"
        issue: "{{ results.meta.key }}"
        operation: "transition"
        status: "Complete"
        comment: >-
          Found that device configuration was partially applied, some
          configuration was missing.

          Resolved issue by applying missing configuration to device.
        fields:
          resolution:
            name: "Done"
    - ansible.builtin.pause:
        prompt: "Press 'Enter' to continue with playbook"
    - name: "Close Jira problem"
      community.general.jira:
        uri: "{{ jira_uri }}"
        username: "{{ jira_username }}"
        password: "{{ jira_password }}"
        issue: "{{ results.meta.key }}"
        operation: "transition"
        status: "Close"
