---
- name: "Create, update, and close a Jira change request"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Create Jira change request"
      community.general.jira:
        uri: "{{ jira_uri }}"
        username: "{{ jira_username }}"
        password: "{{ jira_password }}"
        project: "GLOB"
        operation: "create"
        summary: "Example Change Request"
        description: >
          Change request automatically opened by Ansible demonstrating how
          Ansible can open a new change request.
        issuetype: "[System] Change"
        fields:
          labels:
            - ansible
      register: results
    - name: "Display Jira issue key"
      ansible.builtin.debug:
        var: results.meta.key
    - ansible.builtin.pause:
        prompt: "Press 'Enter' to continue with playbook"
    - name: "Assign Jira change request to user account"
      community.general.jira:
        uri: "{{ jira_uri }}"
        username: "{{ jira_username }}"
        password: "{{ jira_password }}"
        issue: "{{ results.meta.key }}"
        operation: "edit"
        account_id: "70121:2dbae1f5-6dca-4b0f-bc3d-353c20e542d2"
    - ansible.builtin.pause:
        prompt: "Press 'Enter' to continue with playbook"
    - name: "Modify change request status to Awaiting Implementation"
      community.general.jira:
        uri: "{{ jira_uri }}"
        username: "{{ jira_username }}"
        password: "{{ jira_password }}"
        issue: "{{ results.meta.key }}"
        operation: "transition"
        status: "Standard change"
    - ansible.builtin.pause:
        prompt: "Press 'Enter' to continue with playbook"
    - name: "Schedule change request"
      community.general.jira:
        uri: "{{ jira_uri }}"
        username: "{{ jira_username }}"
        password: "{{ jira_password }}"
        issue: "{{ results.meta.key }}"
        operation: "edit"
        comment: "Scheduling change request."
        fields:
          customfield_10044: "2022-02-04T07:00:00.000-0500"
          customfield_10045: "2022-02-04T11:00:00.000-0500"
    - ansible.builtin.pause:
        prompt: "Press 'Enter' to continue with playbook"
    - name: "Implement change request"
      community.general.jira:
        uri: "{{ jira_uri }}"
        username: "{{ jira_username }}"
        password: "{{ jira_password }}"
        issue: "{{ results.meta.key }}"
        operation: "transition"
        status: "Implement"
        comment: "Implementing change request."
    - ansible.builtin.pause:
        prompt: "Press 'Enter' to continue with playbook"
    - name: "Complete change request"
      community.general.jira:
        uri: "{{ jira_uri }}"
        username: "{{ jira_username }}"
        password: "{{ jira_password }}"
        issue: "{{ results.meta.key }}"
        operation: "transition"
        status: "Complete"
        comment: "Completing change request."
